# logging configuration
logging:
  file: logs/qa-tool.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    in.indigenous.qa: DEBUG
    
# Spring MVC configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
          - /**
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
    enabled: true
    url: jdbc:mariadb://localhost:3306/qa
    user: root
    drop-first: false
    contexts: dev
# Server configuration
server:
  port: 8082
  servlet:
    context-path: /qa

# Application configuration
application:
  name: QATool
  version: 0
  major:
    version: 0
  minor:
    version: 2
  slogan: Quality Matters
  
# Page related configurations
home:
  title: Home